data sources:

- https://fdc.nal.usda.gov/download-datasets.html
- https://www.ers.usda.gov/data-products/fruit-and-vegetable-prices.aspx
- https://www.kaggle.com/datasets/thedevastator/the-nutritional-content-of-food-a-comprehensive
- https://www.kaggle.com/datasets/trolukovich/nutritional-values-for-common-foods-and-products
- https://www.kaggle.com/datasets/thunderz/food-data


inspiration sources:

- https://nutritionj.biomedcentral.com/articles/10.1186/s12937-019-0496-5
- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2954450/
- https://www.healthline.com/nutrition/29-cheap-healthy-foods
- https://nutritionfacts.org/blog/best-nutrition-bang-for-your-buck/

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# data source:
# https://www.kaggle.com/datasets/thunderz/food-data

df = pd.read_csv('data/food-data/usda_foundation_food_data.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12044 entries, 0 to 12043
Columns: 235 entries, name to Total dietary fiber (AOAC 2011.25)
dtypes: float64(212), int64(22), object(1)
memory usage: 21.6+ MB

In [4]:
df.head()

,name,Nitrogen,Protein,Total lipid (fat),"Carbohydrate, by difference",Ash,Energy,Starch,Sucrose,Glucose (dextrose),...,22:3,20:4 c,20:5 c,22:5 c,22:6 c,20:2 c,trans-beta-Carotene,trans-Lycopene,"Cryptoxanthin, alpha",Total dietary fiber (AOAC 2011.25)
0,"hummus, commercial",1.18,7.35,17.10,14.90,1.97,960.0,8.12,0.18,0.00,...,0.0,0.005,0.0,0.000,0.0,0.005,0.000000,0.0,0.0,0.0
1,"milk, reduced fat, fluid, 2% milkfat, with add...",0.53,3.35,1.90,4.91,0.75,209.0,0.00,0.00,0.00,...,0.0,0.003,0.0,0.001,0.0,0.000,0.000002,0.0,0.0,0.0
2,"tomatoes, grape, raw",0.13,0.83,0.63,5.51,0.56,113.0,0.00,0.00,0.00,...,0.0,0.000,0.0,0.000,0.0,0.000,0.000393,0.0,0.0,0.0
3,"salt, table, iodized",0.00,0.00,0.00,0.00,99.00,0.0,0.00,0.00,0.00,...,0.0,0.000,0.0,0.000,0.0,0.000,0.000000,0.0,0.0,0.0
4,"beans, snap, green, canned, regular pack, drai...",0.17,1.04,0.39,4.11,0.89,86.0,0.00,0.00,0.65,...,0.0,0.000,0.0,0.000,0.0,0.000,0.000000,0.0,0.0,0.0

In [13]:
df.head(1).T.iloc[200:]

                                        0
20:3 n-3                              0.0
20:3 n-6                              0.0
20:4 n-6                                0
18:3i                                 0.0
21:5                                    0
22:4                                  0.0
18:1-11 t (18:1t n-7)                   0
20:3 n-9                              0.0
Sugars, total including NLEA            0
5:0                                   0.0
7:0                                   0.0
9:0                                   0.0
21:0                                  0.0
23:0                                  0.0
12:1                                  0.0
14:1 c                                0.0
17:1 c                              0.007
20:1 c                              0.084
20:1 t                                0.0
22:1 n-9                            0.001
22:1 n-11                             0.0
18:2 c                               6.81
18:3 c                              0.656
18:3 t                                0.0
20:3 c                                0.0
22:3                                  0.0
20:4 c                              0.005
20:5 c                                0.0
22:5 c                                0.0
22:6 c                                0.0
20:2 c                              0.005
trans-beta-Carotene                   0.0
trans-Lycopene                        0.0
Cryptoxanthin, alpha                  0.0
Total dietary fiber (AOAC 2011.25)    0.0

In [ ]:
# will likely not use this data set. Only 235 food records